version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: newsletter-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newsletter-network

networks:
  newsletter-network:
    driver: bridge

volumes:
  postgres_data: 