spring:
  application:
    name: api

# Swagger UI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
ai:
  gemini:
    key: ${AI_GEMINI_KEY:}
