spring:
  application:
    name: api
  config:
    import:
      - postgresql.yml

# Swagger UI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
