# Nginx 전용 Docker Compose (Blue-Green 배포용)
services:
  nginx:
    image: nginx:alpine
    container_name: newsletter-nginx
    restart: always
    user: "0:0"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-blue-green.conf:/etc/nginx/nginx.conf:ro
      - ./active-env.conf:/etc/nginx/active-env.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - newsletter-network

networks:
  newsletter-network:
    driver: bridge
    external: true
