spring:
  profiles:
    active: dev
  application:
    name: newsletter-feeder-batch
  mail:
    host: pop.gmail.com
    port: 995
    username: ${MAIL_USER_NAME:}
    password: ${MAIL_PASSWORD:}
    protocol: pop3s
    properties:
      mail:
        pop3s:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 995
        store:
          protocol: pop3s
        debug: false

management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.integration: WARN
    org.springframework.mail: WARN
    jakarta.mail: WARN
    com.nexters.newsletterfeeder: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


ai:
  gemini:
    key: ${GEMINI_API_KEY:}
