spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/newsletter}
    username: ${SPRING_DATASOURCE_USERNAME:newsletter}
    password: ${SPRING_DATASOURCE_PASSWORD:newsletter123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true 