name: PR Automation

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    name: Auto Assign
    runs-on: ubuntu-latest
    
    steps:
    - name: Auto assign PR
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: .github/auto-assign.yml 